server:
  port: 18888

spring:
  application:
    name: ts-assurance-service
  data:
    mongodb:
      host: ts-assurance-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

swagger:
  controllerPackage: assurance.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
