server:
  port: 12386

spring:
  application:
    name: ts-execute-service
swagger:
  controllerPackage: execute.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
