server:
  port: 16114

spring:
  application:
    name: ts-admin-travel-service

swagger:
  controllerPackage: admintravel.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
