server:
  port: 16115

spring:
  application:
    name: ts-admin-user-service

swagger:
  controllerPackage: adminuser.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
