server:
  port: 18767

spring:
  application:
    name: ts-admin-basic-info-service

swagger:
  controllerPackage: adminbasic.microservic
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
