#spring:
#  data:
#    mongodb:
#      host: ts-preserve-mongo
##      username: user
##      password: ${MONGODB_PASSWORD}
##      database: piggymetrics
#      port: 27017

# HTTP Server
server:
  port: 14568  # HTTP (Tomcat) port

spring:
  application:
    name: ts-preserve-service

swagger:
  controllerPackage: preserve.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
