server:
  port: 18885  # HTTP (Tomcat) port

spring:
  application:
    name: ts-cancel-service

swagger:
  controllerPackage: cancel.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
