server:
  port: 18898

spring:
  application:
    name: ts-seat-service

swagger:
  controllerPackage: seat.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
