server:
  port: 15680

spring:
  application:
    name: ts-basic-service

swagger:
  controllerPackage: fdse.microservice.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
