server:
  port: 16113

spring:
  application:
    name: ts-admin-route-service

swagger:
  controllerPackage: adminroute.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
