# HTTP Server
server:
  port: 12346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel-service
  data:
    mongodb:
      host: ts-travel-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
#  zipkin:
#    baseUrl: http://192.168.1.225:9411/
#  sleuth:
#    sampler:
#      percentage: 1.0
swagger:
  controllerPackage: travel.controller

opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
