server:
  port: 12340
spring:
  application:
    name: ts-auth-service
  data:
    mongodb:
      host: ts-auth-mongo
      database: ts-auth-mongo
      port: 27017

swagger:
  controllerPackage: auth.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.224:14268/api/traces
