server:
  port: 16112

spring:
  application:
    name: ts-admin-order-service


swagger:
  controllerPackage: adminorder.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
