spring:
  application:
    name: ts-route-plan-service

# HTTP Server
server:
  port: 14578 # HTTP (Tomcat) port


swagger:
  controllerPackage: plan.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
