# HTTP Server
server:
  port: 15681  # HTTP (Tomcat) port

spring:
  application:
    name: ts-ticketinfo-service


swagger:
  controllerPackage: ticketinfo.controller
opentracing:
  jaeger:
    http-sender:
      url: http://192.168.1.225:14268/api/traces
